language: node_js
node_js:
- lts/*
os:
- linux
dist: focal
branches:
  only:
  - nuxt
cache: yarn
script:
- yarn
- yarn lint
- yarn generate
deploy:
  provider: pages
  strategy: git
  edge: true
  fqdn: wonderland.mrsmc.xyz
  token:
    secure: qFKkXsxr+nPcTh9VNCselhB3yIBb/BP8KqIvjzGw7yqxg0MF6xwsAYCCv/C61reW8Fnnaeyf8s9DFN84RsuAEqxOxYqm5dygi/ymOKLSTs2jm3rHhCdg9WgXGBOldR90TS5UdAm/cnar0O8Dn6Ek/SvANS7NH4Z10auHMGtDR7AmaE9NYITSCGTdfWGYvmpBzqzo6Ja7uVjLYpc9p6kwoREPXLQlm1Jh5NUfkZjyAkcBqPlhkpCUCuZjdi7OoqREs9L6wysEG25DToHAwUYJVVrypxqLuC0RmnojBnUMvljEx+Xa+WEyHQL1wm3iGMp9SIE6IQmXvK2xFdGh8a0skiY25fYk1XOqzRsV8k4hIYahqpm4ellljpNS2siFYXkLGYWOmrX5FqRKl5YqcLVVHmkGbWFtvLSErkurjo8xgWiXrsiyYWeH2W6/YmYovB3iscWxXLliGAkdkHbZyLXHqtd0BHOUjBuoySkvabiptvooIJYzjN8QrgfS7n9M3vRy56HZsc0QSiK4rK3MePQKM9TQZWgixTNjphavPBmZqLzt7Ldd3A1EosJVPHoEXGvwPmZTdVnIkjnK+Jep8ry3Qxkayy2kxIH00n/TRDdbFW8HFmbPiMewrQYfUGNunR1hz64JFjhNZuCqXI4zEpxAJFYL3hPq4ez/McsbzOjjz2Q=
